import {
    Prisma,
    UserRole,
    UserStatus,
    VoteType,
    Level,
    CourseStatus,
    ContentType,
    VideoStatus,
    type User,
    type Category,
    type FAQ,
    type Banner,
    type Course,
    type Content,
    type Certificate,
    type Review,
    type Question,
    type Answer,
    type Vote,
    type Benefit,
    type Prerequisite,
    type Link,
    type VideoMetadata,
    type VideoProgress,
    type MarkAsCompleted,
    type DemoMetadata,
} from "@prisma/client";

export {
    UserRole,
    UserStatus,
    CourseStatus,
    Level,
    VoteType,
    ContentType,
    VideoStatus,
    User,
    Category,
    FAQ,
    Banner,
    Course,
    Content,
    Certificate,
    Review,
    Question,
    Answer,
    Vote,
    Benefit,
    Prerequisite,
    Prisma,
    Link,
    DemoMetadata,
    VideoMetadata,
    VideoProgress,
    MarkAsCompleted
}