import { FcGoogle } from "react-icons/fc";
import { FaGithub, FaUser, FaUserShield } from "react-icons/fa";
import {
    ExclamationTriangleIcon,
    CheckCircledIcon,
    SunIcon,
    MoonIcon,
    LaptopIcon,
    SlashIcon,
    ArrowDownIcon,
    ArrowUpIcon,
    CaretSortIcon,
    EyeNoneIcon,
    Cross2Icon,
    MixerHorizontalIcon,
    ChevronLeftIcon,
    ChevronRightIcon,
    DoubleArrowLeftIcon,
    DoubleArrowRightIcon,
    CheckIcon,
    PlusCircledIcon,
    DownloadIcon,
    CircleBackslashIcon,
    ArchiveIcon,
    PersonIcon,
    TrashIcon,
    DotsHorizontalIcon,
    ReloadIcon,
    PlusIcon,
    ImageIcon,
    GearIcon,
} from "@radix-ui/react-icons";
import { IoEyeOffOutline, IoEyeOutline } from "react-icons/io5";
import {
    HiOutlineMenuAlt3,
    HiOutlineUserCircle,
    HiMinus,
    HiPlus,
} from "react-icons/hi";
import {
    Sun,
    Moon,
    Search,
    MinusIcon,
    ChevronDown,
    ChevronLeft,
    MenuIcon,
    LayoutDashboardIcon,
    User,
    LogOutIcon,
    User2Icon,
    CircuitBoardIcon,
    CheckCircleIcon,
    XCircleIcon,
    ShieldIcon,
    UserIcon,
    Grip,
    CirclePlay,
    Book,
    HelpCircle,
    PuzzleIcon,
    RocketIcon,
    CrownIcon,
    StarIcon,
    TrophyIcon,
    TvMinimalPlayIcon,
    FileIcon
} from "lucide-react";
import { RiLockPasswordLine } from "react-icons/ri";
import {
    AiOutlineLogout,
    AiOutlineCamera,
    AiOutlineUser,
    AiOutlineStar,
    AiFillStar,
    AiOutlineUnorderedList,
    AiOutlineDelete,
} from "react-icons/ai";
import { BsStarHalf, BsLink45Deg } from "react-icons/bs";
import { BiPencil } from "react-icons/bi";
import { SiCoursera } from "react-icons/si";
import { MdOutlineEmail, MdDrafts } from "react-icons/md";
import { IoMdNotificationsOutline, IoMdCheckmark, IoIosCheckmarkCircleOutline } from "react-icons/io"
import { RxArrowRight, RxArrowLeft, RxCross1 } from "react-icons/rx";
import { RiAddCircleLine } from "react-icons/ri";
import { TiTick } from "react-icons/ti";
import {
    PiArrowFatLinesDown,
    PiArrowFatLinesUp,
    PiArrowFatLinesUpFill,
    PiArrowFatLinesDownFill
} from "react-icons/pi";
import { LiaComments } from "react-icons/lia";

export {
    FaGithub,
    FcGoogle,
    ExclamationTriangleIcon,
    CheckCircledIcon,
    IoEyeOffOutline,
    IoEyeOutline,
    HiOutlineMenuAlt3,
    HiOutlineUserCircle,
    Sun,
    Moon,
    Search,
    AiOutlineLogout,
    SiCoursera,
    RiLockPasswordLine,
    FaUser,
    AiOutlineCamera,
    MdOutlineEmail,
    AiOutlineUser,
    AiOutlineStar,
    AiFillStar,
    BsStarHalf,
    AiOutlineUnorderedList,
    HiMinus,
    HiPlus,
    PlusIcon,
    MinusIcon,
    IoMdNotificationsOutline,
    RxArrowRight,
    RxArrowLeft,
    RxCross1,
    RiAddCircleLine,
    BiPencil,
    AiOutlineDelete,
    ChevronDown,
    ChevronLeft,
    MenuIcon,
    BsLink45Deg,
    IoMdCheckmark,
    IoIosCheckmarkCircleOutline,
    TiTick,
    LayoutDashboardIcon,
    User,
    LogOutIcon,
    User2Icon,
    CircuitBoardIcon,
    SunIcon,
    MoonIcon,
    LaptopIcon,
    SlashIcon,
    ArrowDownIcon,
    ArrowUpIcon,
    CaretSortIcon,
    EyeNoneIcon,
    Cross2Icon,
    MixerHorizontalIcon,
    ChevronLeftIcon,
    ChevronRightIcon,
    DoubleArrowLeftIcon,
    DoubleArrowRightIcon,
    CheckIcon,
    PlusCircledIcon,
    DownloadIcon,
    CheckCircleIcon,
    XCircleIcon,
    CircleBackslashIcon,
    ArchiveIcon,
    UserIcon,
    ShieldIcon,
    PersonIcon,
    TrashIcon,
    DotsHorizontalIcon,
    FaUserShield,
    ReloadIcon,
    Grip,
    ImageIcon,
    CirclePlay,
    Book,
    PuzzleIcon,
    RocketIcon,
    CrownIcon,
    HelpCircle,
    StarIcon,
    TrophyIcon,
    GearIcon,
    MdDrafts,
    TvMinimalPlayIcon,
    FileIcon,
    PiArrowFatLinesUp,
    PiArrowFatLinesDown,
    PiArrowFatLinesUpFill,
    PiArrowFatLinesDownFill,
    LiaComments
}